### ISSUE TITLE
error on pasting Blocks with subID > 15

### ISSUE THREAD

**Issue by Darkmaxsas** [GTNewHorizons/worldedit-gtnh#8]
This error occurs when trying to place a block with a subID > 15 like  1234:16
this happend to me while trying to place any Inverted Lamp from ProjectRed Illumination 
since they have a ID Range from 3262:16 - 3262:31

Error in Chat:   java.lang.reflect.InvocationTargetException: null

Console Log:
SEVERE: [WorldEdit] An unexpected error while handling a WorldEdit command
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at RFB-Launch//com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:258)
        at RFB-Launch//com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125)
        at RFB-Launch//com.sk89q.worldedit.extension.platform.CommandManager.handleCommand(CommandManager.java:301)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at RFB-Launch//com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:55)
        at RFB-Launch//com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:74)
        at RFB-Launch//com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:197)
        at RFB-Launch//com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:183)
        at RFB-Launch//com.sk89q.worldedit.forge.ForgeWorldEdit.onCommandEvent(ForgeWorldEdit.java:180)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_1304_ForgeWorldEdit_onCommandEvent_CommandEvent.invoke(.dynamic)
        at RFB-Launch//cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
        at RFB-Launch//cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
        at RFB-Launch//net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:54)
        at RFB-Launch//net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739)
        at RFB-Launch//net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718)
        at RFB-Launch//net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
        at RFB-Launch//net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
        at RFB-Launch//net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
        at RFB-Launch//net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
        at RFB-Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
        at RFB-Launch//net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
        at RFB-Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
        at RFB-Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
        at RFB-Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.IllegalArgumentException: Can't have a block data value above 15 (16 given)
        at RFB-Launch//com.sk89q.worldedit.blocks.BaseBlock.internalSetData(BaseBlock.java:186)
        at RFB-Launch//com.sk89q.worldedit.blocks.BaseBlock.<init>(BaseBlock.java:107)
        at RFB-Launch//com.sk89q.worldedit.forge.TileEntityBaseBlock.<init>(TileEntityBaseBlock.java:28)
        at RFB-Launch//com.sk89q.worldedit.forge.ForgeWorld.getBlock(ForgeWorld.java:427)
        at RFB-Launch//com.sk89q.worldedit.EditSession.getBlock(EditSession.java:459)
        at RFB-Launch//com.sk89q.worldedit.function.block.ExtentBlockCopy.apply(ExtentBlockCopy.java:63)
        at RFB-Launch//com.sk89q.worldedit.function.RegionMaskingFilter.apply(RegionMaskingFilter.java:50)
        at RFB-Launch//com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:54)
        at RFB-Launch//com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:85)
        at RFB-Launch//com.sk89q.worldedit.function.operation.DelegateOperation.resume(DelegateOperation.java:49)
        at RFB-Launch//com.sk89q.worldedit.function.operation.Operations.completeLegacy(Operations.java:51)
        at RFB-Launch//com.sk89q.worldedit.EditSession.stackCuboidRegion(EditSession.java:1228)
        at RFB-Launch//com.sk89q.worldedit.command.RegionCommands.stack(RegionCommands.java:290)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        ... 26 more

Infos on my install:
GTNH 2.6.1
Standard Forge MP Server
WE Version: v0.0.6  (but it also happens with the latest 1.7.10 official WE version)

**Comment by spacebuilder2020** [comment]
Looking at this error, I think the changes I made in https://github.com/GTNewHorizons/worldedit-gtnh/pull/14 to support larger ids and data blocks will fix this error.
